class ChordList {
  static List<List<String>> getMajMinChordList() {
    return [
      ["CM", 'C E G'],
      ["C#M", 'C# E# G#'],
      ["DM", 'D F# A'],
      ["EbM", 'Eb G Bb'],
      ["EM", 'E G# B'],
      ["FM", 'F A C'],
      ["F#M", 'F# A# C#'],
      ["GM", 'G B D'],
      ["AbM", 'Ab C Eb'],
      ["AM", 'A C# E'],
      ["BbM", 'Bb D F'],
      ["BM", 'B D# F#'],
      ["Cm", 'C Eb G'],
      ["C#m", 'C# E G#'],
      ["Dm", 'D F A'],
      ["Ebm", 'Eb Gb B'],
      ["Em", 'E G B'],
      ["Fm", 'F Ab C'],
      ["F#m", 'F# A C#'],
      ["Gm", 'G Bb D'],
      ["Abm", 'Ab Cb Eb'],
      ["Am", 'A C E'],
      ["Bbm", 'Bb Db F'],
      ["Bm", 'B D F#'],
    ];
  }

  static List<List<String>> getFMajChordList() {
    return [
      ['FM', 'F A C'],
      ['FM7', 'F A C E'],
      ['FM9', 'F A C E G'],
      ['Fsus4', 'F Bb C'],
      ['F7sus4', 'F Bb C Eb'],
      ['Gm', 'G Bb D'],
      ['Gm7', 'G Bb D F'],
      ['Gm9', 'G Bb D F A'],
      ['Gsus4', 'G C D'],
      ['Am', 'A C E'],
      ['Am7', 'A C E G'],
      ['Asus4', 'A D E'],
      ['BbM', 'Bb D F'],
      ['Bb6', 'Bb D F G'],
      ['Bbm6', 'Bb Db F G'],
      ['BbM7', 'Bb D F A'],
      ['BbmM7', 'Bb Db F A'],
      ['B7(b5)', 'B Eb F A'],
      ['CM', 'C E G'],
      ['Cm7', 'C Eb G Bb'],
      ['C7', 'C E G Bb'],
      ['Csus4', 'C F G'],
      ['C7sus4', 'C F G Bb'],
      ['C9sus4', 'C F G Bb D'],
      ['Dm', 'D F A'],
      ['Dm7', 'D F A C'],
      ['Dsus4', 'D G A'],
      ['D7sus4', 'D G A C'],
      ['Edim', 'E G Bb'],
      ['Edim7', 'E G Bb Db'],
      ['Em7(b5)', 'E G Bb D'],
    ];
  }
}
