class ChordList {
  static List<List<String>> getMajMinChordList() {
    return [
      ["CM", 'C E G'],
      ["C♯M", 'C♯ E♯ G♯'],
      ["DM", 'D F♯ A'],
      ["E♭M", 'E♭ G B♭'],
      ["EM", 'E G♯ B'],
      ["FM", 'F A C'],
      ["F♯M", 'F♯ A♯ C♯'],
      ["GM", 'G B D'],
      ["A♭M", 'A♭ C E♭'],
      ["AM", 'A C♯ E'],
      ["B♭M", 'B♭ D F'],
      ["BM", 'B D♯ F♯'],
      ["Cm", 'C E♭ G'],
      ["C♯m", 'C♯ E G♯'],
      ["Dm", 'D F A'],
      ["E♭m", 'E♭ G♭ B'],
      ["Em", 'E G B'],
      ["Fm", 'F A♭ C'],
      ["F♯m", 'F♯ A C♯'],
      ["Gm", 'G B♭ D'],
      ["A♭m", 'A♭ C♭ E♭'],
      ["Am", 'A C E'],
      ["B♭m", 'B♭ D♭ F'],
      ["Bm", 'B D F♯'],
    ];
  }

  static List<List<String>> getFMajChordList() {
    return [
      ['FM', 'F A C'],
      ['FM7', 'F A C E'],
      ['FM9', 'F A C E G'],
      ['Fsus4', 'F B♭ C'],
      ['F7sus4', 'F B♭ C E♭'],
      ['Gm', 'G B♭ D'],
      ['Gm7', 'G B♭ D F'],
      ['Gm9', 'G B♭ D F A'],
      ['Gsus4', 'G C D'],
      ['Am', 'A C E'],
      ['Am7', 'A C E G'],
      ['Asus4', 'A D E'],
      ['B♭M', 'B♭ D F'],
      ['B♭6', 'B♭ D F G'],
      ['B♭m6', 'B♭ D♭ F G'],
      ['B♭M7', 'B♭ D F A'],
      ['B♭mM7', 'B♭ D♭ F A'],
      ['B7(♭5)', 'B E♭ F A'],
      ['CM', 'C E G'],
      ['Cm7', 'C E♭ G B♭'],
      ['C7', 'C E G B♭'],
      ['Csus4', 'C F G'],
      ['C7sus4', 'C F G B♭'],
      ['C9sus4', 'C F G B♭ D'],
      ['Dm', 'D F A'],
      ['Dm7', 'D F A C'],
      ['Dsus4', 'D G A'],
      ['D7sus4', 'D G A C'],
      ['Edim', 'E G B♭'],
      ['Edim7', 'E G B♭ D♭'],
      ['Em7(♭5)', 'E G B♭ D'],
    ];
  }
}
